# ===============================
# Application Info
# ===============================
spring.application.name=chat-service
server.port=8083

# ===============================
# Database Configuration
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/chat_service?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password= Sohan@123#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# ===============================
# JPA / Hibernate Configuration
# ===============================


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Kafka Configuration
# ===============================
spring.kafka.bootstrap-servers=localhost:9092

# --- Consumer Config ---
spring.kafka.consumer.group-id=chat-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.value.default.type=com.example.ChatService.Entity.Message
spring.kafka.consumer.properties.spring.json.trusted.packages=com.example.ChatService.DTO


# --- Producer Config (optional for sending messages) ---
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# ===============================
# Logging (Optional but useful)
# ===============================
logging.level.org.springframework.kafka=INFO
logging.level.com.example.ChatService=DEBUG
